# Generated by Django 4.2.15 on 2025-10-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of cuisine', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description of the cuisine', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dish', max_length=50)),
                ('description', models.CharField(help_text='Description of the dish', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the dish', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=50)),
                ('address', models.CharField(help_text='Address of the restaurant', max_length=200)),
                ('city', models.CharField(help_text='City where the restaurant is located', max_length=30)),
                ('cost_for_two', models.IntegerField(help_text='Average cost for two people')),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='non_veg', help_text='Type of food: Veg / Non-veg / Vegan', max_length=15)),
                ('open_status', models.BooleanField(default=True, help_text='Is the restaurant currently open?')),
                ('spotlight', models.BooleanField(default=False, help_text='Set True to display the restaurant on homepage')),
                ('cuisines', models.ManyToManyField(help_text='Cuisines served by the restaurant', related_name='restaurants', to='restaurants.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Images of the restaurant', null=True, upload_to='restaurant_photos/')),
                ('restaurant', models.ForeignKey(help_text='The name of the restaurant of the given photo', on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_photos', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image of the menu item', null=True, upload_to='menu_items/')),
                ('menu_item', models.ForeignKey(help_text='Represents the menu item of the given image', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_photos', to='restaurants.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(help_text='The restaurant that offers this menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant'),
        ),
    ]
