# Generated by Django 4.2.15 on 2025-11-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visited_at']},
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visited',
            new_name='visited_at',
        ),
    ]
