# Generated by Django 4.2.15 on 2025-11-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by_user', to='restaurants.restaurant'),
        ),
    ]
